### ISSUE TITLE
emm我想我在复现过程中发现了一些问题

### ISSUE THREAD

**Issue by y159357** [Snowming04/The-Hacker-Playbook-3-Translation#12]
以下是我在复现中遇到的一些问题（如果是我的错误，还请译者纠正）：
1.在pdf中34页knockpy的使用中，提到了使用-u参数，我在复现时发现貌似没有这个参数，所以我使用了-w参数
2.在pdf中36页git-all-secrets的使用中，提到了将结果文件从容器中提取到主机，我想那段代码并不完全，在那段代码结尾没有指明将目标文件提取到主机的哪个文件，我想应该改为
`docker cp <container-id>:/data/results.txt ./results.txt`

**Comment by Snowming04** [comment]
> 以下是我在复现中遇到的一些问题（如果是我的错误，还请译者纠正）：
> 1.在pdf中34页knockpy的使用中，提到了使用-u参数，我在复现时发现貌似没有这个参数，所以我使用了-w参数
> 2.在pdf中36页git-all-secrets的使用中，提到了将结果文件从容器中提取到主机，我想那段代码并不完全，在那段代码结尾没有指明将目标文件提取到主机的哪个文件，我想应该改为
> `docker cp <container-id>:/data/results.txt ./results.txt`

感谢，已更正
