### ISSUE TITLE
第1章 赛前准备——安装(商用 ATT&CK 矩阵 - Windows版，图片内容重复 )

### ISSUE THREAD

**Issue by MyKings** [Snowming04/The-Hacker-Playbook-3-Translation#3]
如下图红色标注，地址：https://github.com/Snowming04/The-Hacker-Playbook-3-Translation/blob/master/content/1_pregame_the_setup.md#%E7%BA%A2%E9%98%9F%E7%9A%84%E6%A0%B8%E5%BF%83%E5%B7%A5%E5%85%B7

<img width="779" alt="1-2" src="https://user-images.githubusercontent.com/7788116/54573914-29635100-4a29-11e9-8e2e-37d8e1b439e6.PNG">

**Comment by Snowming04** [comment]
已修改图片。
