### ISSUE TITLE
“APT组织与方法持续更新列表”的链接有误

### ISSUE THREAD

**Issue by dom2q** [Snowming04/The-Hacker-Playbook-3-Translation#6]
如下图所示：
![image](https://user-images.githubusercontent.com/2830755/54610281-a0333500-4a8f-11e9-9024-6e5d404036d4.png)
经测试，可用链接为：http://bit.ly/2GZb8eW

**Comment by Snowming04** [comment]
已更正，其实这是一个只有 PDF 才有的问题。
已经重新生成并替换了 PDF。 
谢谢~
